const txt2imgReqBody = {
  "prompt": "masterpiece, best quality, 4k, hires, Ray tracing, hdr, ",
  "negative_prompt": "EasyNegativeV2, badhandv4, watermark, illustration, 3d, sepia, painting, cartoons, sketch, (worst quality:2), (low quality:2), (normal quality:2), lowres, bad anatomy, bad hands, normal quality, ((monochrome)), ((grayscale:1.2)),  analog, analogphoto, signatre, logo,2 faces",
  "styles": [
    "string"
  ],
  "seed": -1,
  "subseed": -1,
  "subseed_strength": 0,
  "seed_resize_from_h": -1,
  "seed_resize_from_w": -1,
  "sampler_name": "DPM++ SDE Karras",
  "batch_size": 1,
  "n_iter": 1,
  "steps": 10,
  "cfg_scale": 7,
  "width": 16,
  "height": 16,
  "restore_faces": true,
  "tiling": false,
  "do_not_save_samples": false,
  "do_not_save_grid": false,
  "eta": 0,
  "denoising_strength": 0,
  "s_min_uncond": 0,
  "s_churn": 0,
  "s_tmax": 0,
  "s_tmin": 0,
  "s_noise": 0,
  "override_settings": {},
  "override_settings_restore_afterwards": true,
  "refiner_checkpoint": "",
  "refiner_switch_at": 0,
  "disable_extra_networks": false,
  "comments": {},
  "enable_hr": false,
  "firstphase_width": 0,
  "firstphase_height": 0,
  "hr_scale": 2,
  "hr_upscaler": "string",
  "hr_second_pass_steps": 0,
  "hr_resize_x": 0,
  "hr_resize_y": 0,
  "hr_checkpoint_name": "chilloutmix_NiPrunedFp16",
  "hr_sampler_name": "DPM++ SDE Karras",
  "hr_prompt": "",
  "hr_negative_prompt": "",
  "sampler_index": "DPM++ SDE Karras",
  "script_name": "",
  "script_args": [],
  "send_images": true,
  "save_images": true,
  "alwayson_scripts": {}
}

export default txt2imgReqBody